name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Blog API
        run: |
          docker build -t umer515k/blog-api:latest ./blog-api
          docker push umer515k/blog-api:latest

      - name: Build and Push Auth API
        run: |
          docker build -t umer515k/auth-api:latest ./auth-api
          docker push umer515k/auth-api:latest

      - name: Build and Push Analytics API
        run: |
          docker build -t umer515k/analytics-api:latest ./analytics-api
          docker push umer515k/analytics-api:latest

      - name: Build and Push Apache Proxy
        run: |
          docker build -t umer515k/apache-proxy:latest ./apache
          docker push umer515k/apache-proxy:latest